#!/bin/sh
jarfile=tizenrunner.jar
#all lirbary included in the release package
workspace=`pwd`
if [ ! -r "$workspace/plugin/tizen/$jarfile" ]
then
    echo "can't find $workspace/plugin/tizen/$jarfile"
    exit 1
fi
jarpath="$workspace/plugin/tizen/$jarfile"

#if the tizenrunner depend lirbrary not included in the release package. need to specify -Dcom.tizen.tizenrunner.bindir.
exec java -Xmx128M -Dcom.tizen.tizenrunner.bindir="$workspace" -jar "$jarpath" "$@"
